### ISSUE TITLE
Caching for client index.html

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-deployment#4]
Pretty frequently, I have to do a hard refresh to get the proper client page. Can we adjust caching settings to fix that?

**Comment by rybesh** [comment]
We're not doing anything special with caching on client.perio.do:
https://github.com/periodo/periodo-deployment/blob/master/roles/periodo-client/templates/nginx.conf.j2

```
$ curl -I https://client.staging.perio.do/index.html
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 24 Aug 2019 21:21:11 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 928
Last-Modified: Sat, 26 Oct 1985 08:15:00 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "1dc09d84-3a0"
Accept-Ranges: bytes
```

I can set `Cache-Control:no-cache`, set Last-Modified properly, and, and remove the `ETag` header.

Only for `index.html`? Are there other client files we don't want to have cached?

**Comment by ptgolden** [comment]
> I can set Cache-Control:no-cache, set Last-Modified properly, and, and remove the ETag header.

Yeah, that would be good.

Just index.html is fine. The JS is versioned and the images and map tiles shouldn't ever change.

**Comment by rybesh** [comment]
fixed by https://github.com/periodo/periodo-deployment/commit/de983193e926eb1f9a0b660e47b52b3dceb5ae79
```
$ curl -I https://client.staging.perio.do/index.html
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 27 Aug 2019 15:07:45 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 925
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Tuesday, 27-Aug-2019 15:07:45 GMT
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0
Accept-Ranges: bytes

$ curl -I https://client.staging.perio.do
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 27 Aug 2019 15:08:43 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 925
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Tuesday, 27-Aug-2019 15:08:43 GMT
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0
Accept-Ranges: bytes

$ curl -I https://client.staging.perio.do/periodo-client-4.0.0-15.min.js
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 27 Aug 2019 15:09:58 GMT
Content-Type: application/javascript; charset=utf-8
Content-Length: 3589002
Last-Modified: Sat, 26 Oct 1985 08:15:00 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "1dc09d84-36c38a"
Accept-Ranges: bytes
```

**Comment by ptgolden** [comment]
Cool.

I always forget about combining caching headers. Is there any reason not to set an accurate `Last-Modified` header? Or rather, why have it at all if it's not telling the truth?

**Comment by rybesh** [comment]
For `/index.html`, I think we want to set it to now to ensure it doesn't get cached. But for the other things I could turn it off, I guess.
